# Generated by Django 5.0.2 on 2024-02-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationcenter',
            name='dose',
        ),
    ]
