# Generated by Django 5.0.2 on 2024-02-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_vaccinationcenter_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='dose',
            field=models.ManyToManyField(to='app.dosagedetail'),
        ),
    ]
